/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RepousseRouteImport } from './routes/repousse'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeteoRouteImport } from './routes/meteo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InciRouteImport } from './routes/inci'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as AvantApresRouteImport } from './routes/avant-apres'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as IndexRouteImport } from './routes/index'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RepousseRoute = RepousseRouteImport.update({
  id: '/repousse',
  path: '/repousse',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeteoRoute = MeteoRouteImport.update({
  id: '/meteo',
  path: '/meteo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InciRoute = InciRouteImport.update({
  id: '/inci',
  path: '/inci',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const AvantApresRoute = AvantApresRouteImport.update({
  id: '/avant-apres',
  path: '/avant-apres',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/avant-apres': typeof AvantApresRoute
  '/conseils': typeof ConseilsRoute
  '/diagnostic': typeof DiagnosticRoute
  '/historique': typeof HistoriqueRoute
  '/inci': typeof InciRoute
  '/login': typeof LoginRoute
  '/meteo': typeof MeteoRoute
  '/notifications': typeof NotificationsRoute
  '/panier': typeof PanierRoute
  '/photo': typeof PhotoRoute
  '/plan': typeof PlanRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/register': typeof RegisterRoute
  '/repousse': typeof RepousseRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/avant-apres': typeof AvantApresRoute
  '/conseils': typeof ConseilsRoute
  '/diagnostic': typeof DiagnosticRoute
  '/historique': typeof HistoriqueRoute
  '/inci': typeof InciRoute
  '/login': typeof LoginRoute
  '/meteo': typeof MeteoRoute
  '/notifications': typeof NotificationsRoute
  '/panier': typeof PanierRoute
  '/photo': typeof PhotoRoute
  '/plan': typeof PlanRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/register': typeof RegisterRoute
  '/repousse': typeof RepousseRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/avant-apres': typeof AvantApresRoute
  '/conseils': typeof ConseilsRoute
  '/diagnostic': typeof DiagnosticRoute
  '/historique': typeof HistoriqueRoute
  '/inci': typeof InciRoute
  '/login': typeof LoginRoute
  '/meteo': typeof MeteoRoute
  '/notifications': typeof NotificationsRoute
  '/panier': typeof PanierRoute
  '/photo': typeof PhotoRoute
  '/plan': typeof PlanRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/register': typeof RegisterRoute
  '/repousse': typeof RepousseRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aura'
    | '/avant-apres'
    | '/conseils'
    | '/diagnostic'
    | '/historique'
    | '/inci'
    | '/login'
    | '/meteo'
    | '/notifications'
    | '/panier'
    | '/photo'
    | '/plan'
    | '/profil'
    | '/quiz'
    | '/recipes'
    | '/register'
    | '/repousse'
    | '/shop'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aura'
    | '/avant-apres'
    | '/conseils'
    | '/diagnostic'
    | '/historique'
    | '/inci'
    | '/login'
    | '/meteo'
    | '/notifications'
    | '/panier'
    | '/photo'
    | '/plan'
    | '/profil'
    | '/quiz'
    | '/recipes'
    | '/register'
    | '/repousse'
    | '/shop'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/aura'
    | '/avant-apres'
    | '/conseils'
    | '/diagnostic'
    | '/historique'
    | '/inci'
    | '/login'
    | '/meteo'
    | '/notifications'
    | '/panier'
    | '/photo'
    | '/plan'
    | '/profil'
    | '/quiz'
    | '/recipes'
    | '/register'
    | '/repousse'
    | '/shop'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuraRoute: typeof AuraRoute
  AvantApresRoute: typeof AvantApresRoute
  ConseilsRoute: typeof ConseilsRoute
  DiagnosticRoute: typeof DiagnosticRoute
  HistoriqueRoute: typeof HistoriqueRoute
  InciRoute: typeof InciRoute
  LoginRoute: typeof LoginRoute
  MeteoRoute: typeof MeteoRoute
  NotificationsRoute: typeof NotificationsRoute
  PanierRoute: typeof PanierRoute
  PhotoRoute: typeof PhotoRoute
  PlanRoute: typeof PlanRoute
  ProfilRoute: typeof ProfilRoute
  QuizRoute: typeof QuizRoute
  RecipesRoute: typeof RecipesRoute
  RegisterRoute: typeof RegisterRoute
  RepousseRoute: typeof RepousseRoute
  ShopRoute: typeof ShopRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repousse': {
      id: '/repousse'
      path: '/repousse'
      fullPath: '/repousse'
      preLoaderRoute: typeof RepousseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meteo': {
      id: '/meteo'
      path: '/meteo'
      fullPath: '/meteo'
      preLoaderRoute: typeof MeteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inci': {
      id: '/inci'
      path: '/inci'
      fullPath: '/inci'
      preLoaderRoute: typeof InciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avant-apres': {
      id: '/avant-apres'
      path: '/avant-apres'
      fullPath: '/avant-apres'
      preLoaderRoute: typeof AvantApresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuraRoute: AuraRoute,
  AvantApresRoute: AvantApresRoute,
  ConseilsRoute: ConseilsRoute,
  DiagnosticRoute: DiagnosticRoute,
  HistoriqueRoute: HistoriqueRoute,
  InciRoute: InciRoute,
  LoginRoute: LoginRoute,
  MeteoRoute: MeteoRoute,
  NotificationsRoute: NotificationsRoute,
  PanierRoute: PanierRoute,
  PhotoRoute: PhotoRoute,
  PlanRoute: PlanRoute,
  ProfilRoute: ProfilRoute,
  QuizRoute: QuizRoute,
  RecipesRoute: RecipesRoute,
  RegisterRoute: RegisterRoute,
  RepousseRoute: RepousseRoute,
  ShopRoute: ShopRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
